# Generated by Django 4.2 on 2023-04-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gameuser",
            fields=[
                (
                    "name",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("c_date", models.DateTimeField()),
            ],
        ),
    ]
